# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Bestelling.destroy_all
Cart.destroy_all
ProductSauce.destroy_all
Product.destroy_all
Sauce.destroy_all
Category.destroy_all
Brood.destroy_all

Sauce.create(name:"geen", price:0)
Sauce.create(name:"mayo", price:0.55)
Sauce.create(name:"curry", price:0.55)
Sauce.create(name:"mayo/curry", price:0.75)
Sauce.create(name:"speciaal curry", price:0.75)
Sauce.create(name:"pinda", price:0.75)
Sauce.create(name:"oorlog", price:0.75)
Sauce.create(name:"joppie", price:0.75)
Sauce.create(name:"ketchup", price:0.55)
Sauce.create(name:"mayo/ketchup", price:0.75)
Sauce.create(name:"speciaal ketchup", price:0.75)
Sauce.create(name:"chilli", price:0.9)
Sauce.create(name:"loempiasaus", price:0.9)

Brood.create(name:"zacht puntje", price:0.85)
Brood.create(name:"pistolet", price:1.1)
Brood.create(name:"geen", price:0)

vm=Category.create(name:"voordeelmenus", hasSauce:false)
pat=Category.create(name: "patat", hasSauce: true)
sn=Category.create(name: "snacks", hasSauce: true)
menu=Category.create(name: "menus", hasSauce: false)
bg=Category.create(name: "burgers", hasSauce: true)
loemp=Category.create(name: "loempias", hasSauce: false)
ger=Category.create(name: "diverse gerechten", hasSauce: false)
pb=Category.create(name: "partyboxes", hasSauce: false)
br=Category.create(name:"broodjes", hasSauce:true)
#saus=Category.create(name:"bekers sauzen", hasSauce:true)
ms=Category.create(name: "milkshakes", hasSauce: false)

Product.create(name: "klein milkshake",price: 2.1,description: "", category:ms)
Product.create(name: "medium milkshake",price: 3.15,description: "", category:ms)
Product.create(name: "groot milkshake",price: 3.4,description: "",category:ms)

Product.create(name: "kolenkit menu",price: 9.95,description: "portie saté (3 stokjes), kroket, frikandel speciaal, 2 personen patat ", category:vm)
Product.create(name: "super de kolenkit menu",price: 9.95,description: "frikandel, kroket, kaassoufflé, 3 personen patat, beker pindasaus", category:vm)
Product.create(name: "K-menu",price: 9.95,description: "2 vietnamese loempias met chillisaus, kaassoufflé, frikandel, 2 personen patat, beker pindasaus", category:vm)
Product.create(name: "vegetarisch menu",price: 9.95,description: "groente kroket, kaassoufflé, vegetarische bamihap, 2 personen patat, beker pindasaus", category:vm)
Product.create(name: "saté menu met patat",price: 8.7,description: "portie saté, patat en slaatje",category:menu)
Product.create(name: "saté menu met brood",price: 8.7,description:"portie saté, stokbrood met kruidenboter en slaatje" ,category:menu)
Product.create(name: "nasi schotel",price: 9.45,description: "nasi met gebakken ei en frites",category:menu)
Product.create(name: "bami schotel",price: 9.45,description: "bami met gebakken ei en frites",category:menu)
Product.create(name: "spareribs met patat",price: 13.2,description: "spareribs met patat en rauwkost",category:menu)
Product.create(name: "2 hamburger menu",price: 8.7,description: "2 losse hamburgers met patat",category:menu)
Product.create(name: "biefstuk stroganoff",price: 13.2,description: "biefstuk met stroganoffsaus, frites en gemengde sla",category:menu)
Product.create(name: "varkenshaas champignonsaus",price: 13.2,description: "varkenshaas met champignonsaus, frites en gemendge sla",category:menu)
Product.create(name: "shaslick menu",price: 8.7,description: "shaslick met frites en gemengde sla",category:menu)
Product.create(name: "schnitzel menu",price: 8.7,description: "schnitzel met frites en gemengde sla",category:menu)
Product.create(name: "kipschnitzel menu",price: 8.7,description: "kipschnitzel met frites en gemengde sla",category:menu)


Product.create(name: "kinder patat",price: 1.2,description: "", category:pat)
Product.create(name: "patat",price: 1.65,description: "", category:pat)
Product.create(name: "groot patat",price: 3.2,description: "", category:pat)
Product.create(name: "puntzak patat",price: 2.2,description: "", category:pat)

Product.create(name: "hamburger",price: 2.9,description: "nederlandse hamburger", category:bg)
Product.create(name: "kipburger",price: 3.6,description: "krokante halal kipburger", category:bg)
Product.create(name: "hamburger speciaal",price: 3.6,description: "zigeunersaus, mayonaise en gebakken uitjes",  category:bg)
Product.create(name: "hamburger speciaal met ei",price:3.6 ,description: "zigeunersaus, mayonaise en gebakken uitjes met eitje bovenop", category:bg)
Product.create(name: "hamburger hawaai",price: 3.65,description: "", category:bg)
Product.create(name: "cheeseburger",price:3.15 ,description: "", category:bg)

Product.create(name: "frikandel",price:1.35 ,description: "", category:sn)
Product.create(name: "grove frikandel",price: 1.75,description: "", category:sn)
Product.create(name: "kroket",price: 1.2,description: "", category:sn)
Product.create(name: "kipcorn",price: 1.85,description: "", category:sn)
Product.create(name: "nasihap",price: 1.75,description: "", category:sn)
Product.create(name: "bamihap",price: 1.75,description: "", category:sn)
Product.create(name: "bereklauw",price: 2.35,description: "", category:sn)
Product.create(name: "kaassoufflé",price: 1.4,description: "",category:sn)
Product.create(name: "kalfs kroket",price: 1.4,description: "",category:sn)
Product.create(name: "goulash kroket",price: 1.4,description: "",category:sn)
Product.create(name: "van dobben kroket",price: 2,description: "",category:sn)
Product.create(name: "kwekkeboom kroket",price: 2,description: "",category:sn)
Product.create(name: "mini snacks",price: 3.95,description: "2 kipnuggets, 2 gehaktballetjes, 2 mini nasihapjes, 2 mini bamihapjes, 2 mini kaassouffleetjes",category:sn)
Product.create(name: "bitterballen 6",price: 2.05,description: "",category:sn)
Product.create(name: "bitterballen 10",price: 3.4,description: "",category:sn)
Product.create(name: "pikanto",price: 2.15,description: "", category:sn)
Product.create(name: "mexicano",price:2.35 ,description: "",category:sn)
Product.create(name: "smulrol",price: 2.4,description: "",category:sn)
Product.create(name: "saterol",price: 2.4,description: "",category:sn)
Product.create(name: "sitostick",price: 2.4,description: "",category:sn)
Product.create(name: "viandel",price: 1.75,description: "",category:sn)
Product.create(name: "hete donder",price:2.5 ,description: "",category:sn)
Product.create(name: "kaas kroket",price: 1.5,description: "",category:sn)
Product.create(name: "groente kroket",price: 1.5,description: "",category:sn)
Product.create(name: "luxe kaassoufflé",price: 2.3,description: "",category:sn)
Product.create(name: "ribster",price: 2.65,description: "",category:sn)
Product.create(name: "loempia",price:3.45 ,description: "",category:loemp)
Product.create(name: "vietnamese loempia",price:1.45 ,description: "",category:loemp)
Product.create(name: "loempia speciaal",price: 4.3,description: "loempia met pindasaus, ham, ei getopt met loempiasaus",category:loemp)
Product.create(name: "kroepia",price: 3.45,description: "",category:loemp)
Product.create(name: "kipnuggets 10",price: 4.4,description: "",category:sn)
Product.create(name: "kipnuggets 4",price: 1.8,description: "",category:sn)
Product.create(name: "kipfingers",price: 4.4,description: "",category:sn)
Product.create(name: "bonita",price: 2.5,description: "",category:sn)
Product.create(name: "braadworst",price: 1.85,description: "",category:sn)
Product.create(name: "javaanse frikandel",price: 1.95,description: "",category:sn)
Product.create(name: "halve kip",price: 4.9,description: "",category:sn)
Product.create(name: "kipkluifjes 5",price: 3.6,description: "",category:sn)
Product.create(name: "kipknots",price: 2.05,description: "",category:sn)
Product.create(name: "schnitzel",price: 4.7,description: "",category:sn)
Product.create(name: "kipschnitzel",price: 4.7,description: "",category:sn)
Product.create(name: "XXL frikandel",price: 3.0,description: "XXL kipfrikandel",category:sn)
Product.create(name: "NY Chickenstrips 5",price: 4.5,description: "",category:sn)
Product.create(name: "NY Chickenstrips 3",price: 3,description: "",category:sn)


#Product.create(name: "mini nasi hapjes",price: 0,description: "",category:sn)
#Product.create(name: "mini bami hapjes",price: 0,description: "",category:sn)
#Product.create(name: "gehaktballetjes",price: 0,description: "",category:sn)
#Product.create(name: "mini-kaassoufflé",price: 0,description: "",category:sn)
#Product.create(name: "vlammetjes 5",price: 0,description: "",category:sn)

Product.create(name: "saté",price: 4,description: "3 stokjes saté met pindasaus en gebakken uitjes",category:ger)
Product.create(name: "karbonade",price: 4.9,description: "",category:ger)
Product.create(name: "shaslick",price: 5.8,description: "",category:ger)
Product.create(name: "haassaté",price: 5.9,description: "3 stokjes haassaté",category:ger)
Product.create(name: "spareribs",price: 8.5,description: "malse gemarineerde spareribs",category:ger)


Product.create(name: "party-box",price: 17.95,description: "mini nasi(10), mini bami(10), mini gehaktballetjes(10), kipnuggets(10) en bitterballen(10)",category:pb)
Product.create(name: "party-schaal",price: 30.6,description: "mini nasi(10), mini bami(10), mini gehaktballetjes(10), kipnuggets(15), mini kaassoufflé(10) en bitterballen(15)",category:pb)
Product.create(name: "super-schaal",price: 48.6,description: "",category:pb)